"""Add user_id foreign key to tasks table

Revision ID: 72bd1ea036be
Revises: b1a2c3d4e5f6
Create Date: 2026-02-02 15:26:18.754975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "72bd1ea036be"
down_revision: Union[str, Sequence[str], None] = "b1a2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("tasks")]

    # Add column if it doesn't exist
    if "user_id" not in columns:
        op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=True))
    else:
        # Column exists - check if there are NULL values and clean them up
        result = conn.execute(
            sa.text("SELECT COUNT(*) FROM tasks WHERE user_id IS NULL")
        )
        null_count = result.scalar()
        if null_count > 0:
            # Delete tasks without users
            conn.execute(sa.text("DELETE FROM tasks WHERE user_id IS NULL"))
            conn.commit()

    # Check if foreign key already exists
    foreign_keys = inspector.get_foreign_keys("tasks")
    fk_exists = any(
        "user_id" in fk.get("constrained_columns", []) for fk in foreign_keys
    )

    # For SQLite, we need to recreate the table to add constraints
    # But first, let's try a simpler approach - just add the foreign key if possible
    if not fk_exists:
        # SQLite doesn't support adding foreign keys to existing tables easily
        # We'll use batch_alter_table which recreates the table
        try:
            with op.batch_alter_table("tasks", schema=None) as batch_op:
                batch_op.alter_column("user_id", nullable=False)
                batch_op.create_foreign_key(
                    "fk_tasks_user_id", "users", ["user_id"], ["id"]
                )
        except Exception:
            # If batch_alter fails, manually create the constraint
            # Note: SQLite doesn't enforce foreign keys by default, but we'll add it for documentation
            pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_constraint("fk_tasks_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
