"""Add estimated_completion_time to tasks

Revision ID: ca51c53b8fdb
Revises: 9c0a1b2c3d4e
Create Date: 2026-02-02 15:46:19.076001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ca51c53b8fdb"
down_revision: Union[str, Sequence[str], None] = "9c0a1b2c3d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("estimated_completion_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "estimated_completion_time")
    # ### end Alembic commands ###
